exports('getCoreObject', function() return SLX end)
exports('getLocalPlayer', function() return SLX.LocalPlayer end)
exports('getJob', function() return SLX.LocalPlayer.job end)
exports('getMoney', function() return SLX.LocalPlayer.money end)
exports('getGroup', function() return SLX.LocalPlayer.group end)
exports('getStatus', function() return SLX.LocalPlayer.status end)
exports('getKills', function() return SLX.LocalPlayer.kills end)
exports('getDeaths', function() return SLX.LocalPlayer.deaths end)
exports('getXp', function() return SLX.LocalPlayer.xp end)
exports('isPlayerLoaded', function() return SLX.LocalPlayer.spawned end)
exports('getPlayerId', function() return SLX.LocalPlayer.id end)
exports('ShowNotification', function(message, notifyType, length) SLX.ShowNotification(message, notifyType, length) end)
exports('ShowAdvancedNotification', function(sender, subject, msg, textureDict, iconType, flash, saveToBrief, hudColorIndex) SLX.ShowAdvancedNotification(sender, subject, msg, textureDict, iconType, flash, saveToBrief, hudColorIndex) end)
exports('Progressbar', function(message, length, options) return SLX.Progressbar(message, length, options) end)
exports('CancelProgressbar', function() return SLX.CancelProgressbar() end)
exports('ShowAnnounce', function(message, duration) SLX.ShowAnnounce(message, duration) end)
exports('SpawnVehicle', function(vehicleModel, coords, heading, cb, networked) SLX.Game.SpawnVehicle(vehicleModel, coords, heading, cb, networked) end)
exports('DeleteVehicle', function(vehicle) SLX.Game.DeleteVehicle(vehicle) end)
exports('GetPlayers', function(onlyOtherPlayers, returnKeyValue, returnPeds) return SLX.Game.GetPlayers(onlyOtherPlayers, returnKeyValue, returnPeds) end)
exports('GetClosestPlayer', function(coords) return SLX.Game.GetClosestPlayer(coords) end)
exports('GetVehicleInDirection', function() return SLX.Game.GetVehicleInDirection() end)
exports('GetClosestVehicle', function(coords) return SLX.Game.GetClosestVehicle(coords) end)
exports('GetVehiclesInArea', function(coords, radius) return SLX.Game.GetVehiclesInArea(coords, radius) end)
exports('GetClosestPed', function(coords) return SLX.Game.GetClosestPed(coords) end)
exports('GetWeaponLabel', function(weaponName) return SLX.GetWeaponLabel(weaponName) end)
exports('GetWeaponList', function() return SLX.GetWeaponList() end)
exports('GetPlayersInArea', function(coords, radius) return SLX.Game.GetPlayersInArea(coords, radius) end)
exports('GetClosestObject', function(coords) return SLX.Game.GetClosestObject(coords) end)
exports('GetObjects', function() return SLX.Game.GetObjects() end)
exports('GetPeds', function() return SLX.Game.GetPeds() end)
exports('SpawnObject', function(model, coords, heading, cb) SLX.Game.SpawnObject(model, coords, heading, cb) end)
exports('SpawnLocalObject', function(model, coords, heading, cb) SLX.Game.SpawnLocalObject(model, coords, heading, cb) end)
exports('DeleteObject', function(obj) SLX.Game.DeleteObject(obj) end)
exports('Teleport', function(entity, coords, cb) SLX.Game.Teleport(entity, coords, cb) end)
exports('GetVoiceMode', function() return SLX.GetVoiceMode() end)
exports('GetVoiceRange', function() return SLX.GetVoiceRange() end)
exports('GetVoiceLabel', function() return SLX.GetVoiceLabel() end)
exports('IsPlayerTalking', function() return SLX.IsPlayerTalking() end)
exports('GetKillStreak', function() return SLX.GetKillStreak() end)
exports('GetSkinPresets', function() return SLX.GetSkinPresets() end)
exports('SaveSkinPreset', function(name, skinData) SLX.SaveSkinPreset(name, skinData) end)
exports('getInventory', function() return SLX.LocalPlayer.inventory end)
exports('getInventoryItem', function(itemName) return SLX.LocalPlayer.inventory[itemName] end)
exports('hasInventoryItem', function(itemName, count)
    count = tonumber(count) or 1
    local item = SLX.LocalPlayer.inventory[itemName]
    if not item then return false end
    return item.count >= count
end)
exports('UseItem', function(itemName)
    TriggerServerEvent('slx:useItem', itemName)
end)
exports('getSharedObject', function()
    if ESX then return ESX end
    return SLX
end)
